// The English vocabulary Word Steps plays in.
//
// Hand-picked rather than taken from a dictionary, for two reasons. A ladder is only as
// good as the words around it, so the rhyming families (-ake, -ill, -ore…) are
// deliberately dense: a dense list means a stuck player usually has several ways forward
// instead of one. And a seven-year-old should never be shown a word their parent has to
// explain away, which rules out both the rude corners of a four-letter dictionary and the
// archaic ones — no `thou`, no `adze`.

/** Three-letter words, for the short ladders. */
const WORDS_3: readonly string[] = [
  "ace", "act", "add", "ago", "aid", "ail", "aim", "air", "all", "and", "ant", "any",
  "ape", "apt", "arc", "ark", "arm", "art", "ash", "ask", "asp", "ate", "awe", "awl",
  "axe", "aye",
  "bad", "bag", "ban", "bar", "bat", "bay", "bed", "bee", "beg", "bet", "bib", "bid",
  "big", "bin", "bit", "boa", "bog", "boo", "bop", "bow", "box", "boy", "bro", "bud",
  "bug", "bun", "bus", "but", "buy", "bye",
  "cab", "cam", "can", "cap", "car", "cat", "caw", "cob", "cod", "cog", "coo", "cop",
  "cot", "cow", "coy", "cry", "cub", "cud", "cue", "cup", "cut",
  "dab", "dad", "dam", "day", "den", "dew", "did", "dig", "dim", "din", "dip", "doe",
  "dog", "dot", "dry", "dud", "due", "dug", "duo", "dye",
  "ear", "eat", "ebb", "eel", "egg", "elf", "elk", "elm", "emu", "end", "era", "eve",
  "ewe", "eye",
  "fad", "fan", "far", "fat", "fax", "fed", "fee", "few", "fig", "fin", "fir", "fit",
  "fix", "flu", "fly", "foe", "fog", "for", "fox", "fry", "fun", "fur",
  "gab", "gag", "gal", "gap", "gas", "gel", "gem", "get", "gig", "gnu", "goo", "got",
  "gum", "gut", "guy", "gym",
  "had", "hag", "ham", "has", "hat", "hay", "hem", "hen", "her", "hid", "him", "hip",
  "his", "hit", "hoe", "hog", "hop", "hot", "how", "hub", "hue", "hug", "hum", "hut",
  "ice", "icy", "ill", "imp", "ink", "inn", "ion", "irk", "its", "ivy",
  "jab", "jam", "jar", "jaw", "jay", "jet", "jig", "job", "jog", "jot", "joy", "jug",
  "jut",
  "key", "kid", "kin", "kit",
  "lab", "lad", "lag", "lap", "law", "lax", "lay", "led", "leg", "let", "lid", "lie",
  "lip", "lit", "lob", "log", "lot", "low", "lug", "lye",
  "mad", "man", "map", "mar", "mat", "may", "men", "met", "mid", "mix", "mob", "mom",
  "mop", "mow", "mud", "mug", "mum",
  "nab", "nag", "nap", "nay", "net", "new", "nib", "nip", "nod", "nor", "not", "now",
  "nun", "nut",
  "oak", "oar", "oat", "odd", "ode", "off", "oil", "old", "one", "opt", "orb", "ore",
  "our", "out", "owe", "owl", "own",
  "pad", "pal", "pan", "par", "pat", "paw", "pay", "pea", "peg", "pen", "pep", "pet",
  "pew", "pie", "pig", "pin", "pip", "pit", "ply", "pod", "pop", "pot", "pry", "pug",
  "pun", "pup", "put",
  "rag", "ram", "ran", "rap", "rat", "raw", "ray", "red", "ref", "rib", "rid", "rig",
  "rim", "rip", "rob", "rod", "roe", "rot", "row", "rub", "rug", "run", "rut", "rye",
  "sad", "sag", "sap", "sat", "saw", "sax", "say", "sea", "see", "set", "sew", "she",
  "shy", "sip", "sir", "sit", "six", "ski", "sky", "sly", "sob", "son", "sow", "soy",
  "spa", "spy", "sty", "sub", "sum", "sun",
  "tab", "tad", "tag", "tan", "tap", "tar", "tax", "tea", "tee", "ten", "the", "tie",
  "tin", "tip", "toe", "ton", "too", "top", "tot", "tow", "toy", "try", "tub", "tug",
  "tux", "two",
  "urn", "use",
  "van", "vat", "vet", "vie", "vow",
  "wad", "wag", "war", "was", "wax", "way", "web", "wed", "wee", "wet", "who", "why",
  "wig", "win", "wit", "woe", "wok", "won", "woo", "wow", "wry",
  "yak", "yam", "yap", "yen", "yep", "yes", "yet", "yew", "you", "yum",
  "zap", "zip", "zoo",
];

/** Four-letter words, for the longer ladders. */
const WORDS_4: readonly string[] = [
  "able", "aces", "ache", "acid", "acre", "aged", "aide", "aims", "ajar", "akin", "ally",
  "aloe", "also", "alto", "ants", "apes", "apex", "aqua", "arch", "area", "arid", "arms",
  "army", "atom", "aunt", "auto", "away", "axes", "axis",
  "baby", "back", "bags", "bail", "bait", "bake", "bald", "bale", "ball", "balm", "band",
  "bang", "bank", "barb", "bare", "bark", "barn", "bars", "base", "bash", "bask", "bass",
  "bath", "bats", "bead", "beak", "beam", "bean", "bear", "beat", "beds", "beef", "been",
  "beep", "bees", "beet", "bell", "belt", "bend", "bent", "best", "bets", "bide", "bids",
  "bike", "bill", "bind", "bins", "bird", "bite", "bits", "blip", "blob", "blot", "blow",
  "blue", "blur", "boar", "boat", "body", "boil", "bold", "bolt", "bond", "bone", "bony",
  "book", "boom", "boot", "bore", "born", "boss", "both", "bout", "bowl", "bows", "brag",
  "bran", "bred", "brew", "brim", "brow", "buck", "buds", "buff", "bugs", "bulb", "bulk",
  "bull", "bump", "bunk", "buns", "buoy", "burn", "burp", "bury", "bush", "bust", "busy",
  "buzz", "byte",
  "cabs", "cafe", "cage", "cake", "calf", "call", "calm", "came", "camp", "cane", "cans",
  "cape", "caps", "card", "care", "carp", "cars", "cart", "case", "cash", "cast", "cats",
  "cave", "cell", "cent", "chat", "chef", "chew", "chin", "chip", "chop", "chug", "city",
  "clam", "clan", "clap", "claw", "clay", "clip", "clog", "club", "clue", "coal", "coat",
  "code", "coil", "coin", "cold", "colt", "comb", "come", "cone", "cook", "cool", "cope",
  "cops", "cord", "core", "cork", "corn", "cost", "cosy", "cots", "cove", "cows", "crab",
  "cram", "crew", "crib", "crop", "crow", "cube", "cubs", "cuff", "cups", "curb", "cure",
  "curl", "cute", "cuts",
  "dads", "damp", "dare", "dark", "darn", "dart", "dash", "date", "dawn", "days", "daze",
  "dead", "deaf", "deal", "dear", "debt", "deck", "deed", "deep", "deer", "dens", "dent",
  "desk", "dial", "dice", "diet", "digs", "dime", "dine", "dips", "dirt", "disc", "dish",
  "disk", "dive", "dock", "does", "dogs", "doll", "dome", "done", "doom", "door", "dose",
  "dots", "dove", "down", "doze", "drag", "draw", "drew", "drip", "drop", "drum", "duck",
  "dude", "dues", "duet", "dull", "dump", "dune", "dusk", "dust", "duty", "dyed", "dyes",
  "each", "earn", "ears", "ease", "east", "easy", "eats", "echo", "edge", "eggs", "else",
  "ends", "envy", "epic", "even", "ever", "exam", "exit", "eyes",
  "face", "fact", "fade", "fail", "fair", "fake", "fall", "fame", "fang", "fare", "farm",
  "fast", "fate", "fawn", "fear", "feed", "feel", "fees", "feet", "fell", "felt", "fern",
  "figs", "file", "fill", "film", "find", "fine", "fins", "fire", "firm", "fish", "fist",
  "fits", "five", "fizz", "flag", "flap", "flat", "flaw", "flea", "fled", "flee", "flew",
  "flip", "flop", "flow", "foal", "foam", "foes", "foil", "fold", "folk", "fond", "font",
  "food", "fool", "foot", "ford", "fork", "form", "fort", "foul", "four", "fowl", "free",
  "frog", "from", "fuel", "full", "fume", "fund", "furs", "fuse", "fuss",
  "gain", "gale", "game", "gaps", "gate", "gave", "gaze", "gear", "gems", "germ", "gift",
  "gill", "girl", "give", "glad", "glee", "glow", "glue", "gnat", "goal", "goat", "gold",
  "golf", "gone", "gong", "good", "gown", "grab", "gram", "gray", "grew", "grid", "grim",
  "grin", "grip", "grow", "gulf", "gull", "gulp", "gush", "gust",
  "hail", "hair", "half", "hall", "halt", "hand", "hang", "hard", "hare", "harm", "harp",
  "hash", "hats", "have", "hawk", "hays", "haze", "head", "heal", "heap", "hear", "heat",
  "heed", "heel", "held", "helm", "help", "hens", "herb", "herd", "here", "hero", "hide",
  "high", "hike", "hill", "hilt", "hind", "hint", "hips", "hire", "hits", "hive", "hoax",
  "hold", "hole", "holy", "home", "hood", "hoof", "hook", "hoop", "hope", "horn", "hose",
  "host", "hour", "howl", "huge", "hulk", "hull", "hums", "hunt", "hurl", "hurt", "hush",
  "huts", "hymn",
  "icon", "idea", "idle", "inch", "into", "iris", "iron", "isle", "itch", "item",
  "jade", "jail", "jams", "jars", "jaws", "jazz", "jeep", "jest", "jets", "jobs", "jogs",
  "join", "joke", "jolt", "jugs", "jump", "junk", "just",
  "keel", "keen", "keep", "kelp", "kept", "keys", "kick", "kids", "kiln", "kind", "king",
  "kiss", "kite", "kits", "knee", "knew", "knit", "knob", "knot", "know",
  "lace", "lack", "lads", "lady", "laid", "lake", "lamb", "lame", "lamp", "land", "lane",
  "laps", "lark", "lash", "last", "late", "lawn", "laws", "lays", "lazy", "lead", "leaf",
  "leak", "lean", "leap", "left", "legs", "lend", "lens", "lent", "less", "lick", "lids",
  "life", "lift", "like", "limb", "lime", "limp", "line", "link", "lint", "lion", "lips",
  "list", "live", "load", "loaf", "loan", "lock", "loft", "logs", "lone", "long", "look",
  "loom", "loop", "loot", "lord", "lose", "loss", "lost", "loud", "love", "luck", "lump",
  "lung", "lure", "lush",
  "made", "maid", "mail", "main", "make", "male", "mall", "malt", "mane", "many", "maps",
  "mare", "mark", "mash", "mask", "mass", "mast", "mate", "math", "mats", "maze", "meal",
  "mean", "meat", "meet", "melt", "mend", "menu", "mesh", "mess", "mice", "mild", "mile",
  "milk", "mill", "mind", "mine", "mint", "miss", "mist", "moan", "moat", "mock", "mode",
  "mold", "mole", "monk", "mood", "moon", "moor", "mope", "more", "morn", "moss", "most",
  "moth", "move", "much", "mugs", "mule", "must", "mute",
  "nail", "name", "nape", "navy", "near", "neat", "neck", "need", "nest", "nets", "news",
  "newt", "next", "nice", "nine", "node", "none", "noon", "nope", "nose", "note", "noun",
  "numb", "nuts",
  "oaks", "oars", "oath", "oats", "obey", "odds", "once", "only", "onto", "open", "oval",
  "oven", "over", "owls", "owns",
  "pace", "pack", "pact", "page", "paid", "pail", "pain", "pair", "pale", "palm", "pane",
  "pans", "pant", "park", "part", "pass", "past", "path", "pave", "pawn", "pays", "peak",
  "peal", "pear", "peas", "peck", "peel", "peep", "peer", "pens", "pest", "pets", "pick",
  "pier", "pigs", "pike", "pile", "pill", "pine", "pink", "pins", "pint", "pipe", "pits",
  "pity", "plan", "play", "plea", "plot", "plow", "plug", "plum", "plus", "poem", "poet",
  "pole", "polo", "pond", "pony", "pool", "poor", "pope", "pork", "port", "pose", "post",
  "pots", "pour", "pram", "pray", "prey", "prop", "prow", "pull", "pulp", "pump", "pups",
  "pure", "push",
  "quit", "quiz",
  "race", "rack", "raft", "rage", "raid", "rail", "rain", "rake", "ramp", "rang", "rank",
  "rant", "rare", "rash", "rate", "rats", "rave", "rays", "read", "real", "reap", "rear",
  "reed", "reef", "reel", "rely", "rent", "rest", "ribs", "rice", "rich", "ride", "rift",
  "ring", "rink", "ripe", "rise", "risk", "road", "roam", "roar", "robe", "rock", "rode",
  "role", "roll", "roof", "room", "root", "rope", "rose", "rows", "rude", "rugs", "rule",
  "runs", "rush", "rust",
  "sack", "safe", "sage", "said", "sail", "sake", "sale", "salt", "same", "sand", "sang",
  "sank", "save", "scan", "scar", "seal", "seam", "seas", "seat", "seed", "seek", "seem",
  "seen", "self", "sell", "send", "sent", "sets", "shed", "shin", "ship", "shoe", "shop",
  "shot", "show", "shut", "sick", "side", "sift", "sigh", "sign", "silk", "sill", "silo",
  "sing", "sink", "site", "size", "skin", "skip", "skis", "slab", "slam", "slap", "sled",
  "slid", "slim", "slip", "slot", "slow", "slug", "snap", "snow", "snug", "soak", "soap",
  "sock", "soda", "sofa", "soft", "soil", "sold", "sole", "solo", "some", "song", "soon",
  "sore", "sort", "soul", "soup", "sour", "span", "sped", "spin", "spot", "spun", "stag",
  "star", "stay", "stem", "step", "stew", "stir", "stop", "stub", "stun", "such", "suit",
  "sung", "sunk", "sure", "surf", "swan", "swap", "sway", "swim",
  "tabs", "tack", "tags", "tail", "take", "tale", "talk", "tall", "tame", "tank", "tape",
  "taps", "task", "teal", "team", "tear", "teen", "tell", "tend", "tens", "tent", "term",
  "test", "text", "than", "that", "thaw", "them", "then", "they", "thin", "this", "tick",
  "tide", "tidy", "tied", "ties", "tile", "till", "tilt", "time", "tins", "tiny", "tips",
  "tire", "toad", "toes", "told", "toll", "tomb", "tone", "took", "tool", "toot", "tops",
  "torn", "toss", "tour", "town", "toys", "trap", "tray", "tree", "trim", "trip", "trot",
  "true", "tuba", "tube", "tubs", "tuck", "tugs", "tune", "turn", "tusk", "twig", "twin",
  "type",
  "ugly", "unit", "upon", "used", "user",
  "vain", "vane", "vase", "vast", "veal", "veil", "vent", "verb", "very", "vest", "vine",
  "visa", "void", "vole", "volt", "vote", "vows",
  "wade", "wage", "wags", "wail", "wait", "wake", "walk", "wall", "wand", "want", "ward",
  "warm", "warn", "wart", "wash", "wasp", "wave", "wavy", "waxy", "ways", "weak", "wear",
  "webs", "weed", "week", "weep", "well", "went", "were", "west", "what", "when", "whip",
  "whom", "wick", "wide", "wife", "wigs", "wild", "will", "wilt", "wind", "wing", "wink",
  "wins", "wipe", "wire", "wise", "wish", "wisp", "with", "wits", "woke", "wolf", "wood",
  "wool", "word", "wore", "work", "worm", "worn", "wrap", "wren",
  "yaks", "yams", "yank", "yard", "yarn", "yawn", "year", "yell", "yelp", "yoga", "yolk",
  "your",
  "zeal", "zero", "zest", "zinc", "zips", "zone", "zoom", "zoos",
];

/** English words by length. */
export const ENGLISH_WORDS: Record<number, readonly string[]> = { 3: WORDS_3, 4: WORDS_4 };
