// The vocabulary Word Steps plays in: every word a player is allowed to type, and
// every word a ladder may pass through.
//
// Data only — no DOM, no logic. Both lists are hand-picked rather than taken from a
// dictionary, for two reasons. A ladder is only as good as the words around it, so the
// rhyming families (-ake, -ill, -ore…) are deliberately dense: a dense list means a
// stuck player usually has several ways forward instead of one. And a seven-year-old
// should never be shown a word their parent has to explain, which rules out both the
// rude corners of a four-letter dictionary and the archaic ones — no `thou`, no `adze`.
//
// This module is imported by the page's frontmatter *and* by its client script: the
// build searches the list to check every puzzle has an answer, and the browser searches
// it again to judge the words a player actually types. It is a few kilobytes, which is
// what buys the game its offline life.

/** Kid-familiar three-letter words, for the short ladders. */
export const WORDS_3: readonly string[] = [
  "ace", "act", "add", "ago", "aid", "ail", "aim", "air", "all", "and", "ant", "any",
  "ape", "apt", "arc", "arm", "art", "ash", "ask", "ate", "awe", "axe",
  "bad", "bag", "ban", "bar", "bat", "bay", "bed", "bee", "beg", "bet", "bib", "bid",
  "big", "bin", "bit", "boa", "bog", "boo", "bow", "box", "boy", "bud", "bug", "bun",
  "bus", "but", "buy", "bye",
  "cab", "cam", "can", "cap", "car", "cat", "caw", "cob", "cod", "cog", "cop", "cot",
  "cow", "coy", "cry", "cub", "cue", "cup", "cut",
  "dab", "dad", "dam", "day", "den", "dew", "did", "dig", "dim", "din", "dip", "doe",
  "dog", "dot", "dry", "due", "dug", "duo", "dye",
  "ear", "eat", "eel", "egg", "elf", "elk", "elm", "end", "eve", "ewe", "eye",
  "fad", "fan", "far", "fat", "fax", "fed", "fee", "few", "fig", "fin", "fit", "fix",
  "flu", "fly", "foe", "fog", "for", "fox", "fry", "fun", "fur",
  "gag", "gap", "gas", "gem", "get", "gig", "gnu", "got", "gum", "gut", "guy", "gym",
  "had", "hag", "ham", "has", "hat", "hay", "hem", "hen", "her", "hid", "him", "hip",
  "his", "hit", "hoe", "hog", "hop", "hot", "how", "hub", "hue", "hug", "hum", "hut",
  "ice", "icy", "ill", "ink", "inn", "ion", "its", "ivy",
  "jab", "jam", "jar", "jaw", "jay", "jet", "jig", "job", "jog", "jot", "joy", "jug",
  "key", "kid", "kin", "kit",
  "lab", "lad", "lag", "lap", "law", "lay", "led", "leg", "let", "lid", "lie", "lip",
  "lit", "log", "lot", "low",
  "mad", "man", "map", "mat", "may", "men", "met", "mix", "mob", "mop", "mow", "mud",
  "mug", "mum",
  "nag", "nap", "net", "new", "nib", "nip", "nod", "nor", "not", "now", "nut",
  "oak", "oar", "oat", "odd", "ode", "off", "oil", "old", "one", "orb", "ore", "our",
  "out", "owe", "owl", "own",
  "pad", "pal", "pan", "par", "pat", "paw", "pay", "pea", "peg", "pen", "pep", "pet",
  "pew", "pie", "pig", "pin", "pit", "ply", "pod", "pop", "pot", "pry", "pug", "pun",
  "pup", "put",
  "rag", "ram", "ran", "rap", "rat", "raw", "ray", "red", "rib", "rid", "rig", "rim",
  "rip", "rob", "rod", "roe", "rot", "row", "rub", "rug", "run", "rut", "rye",
  "sad", "sag", "sap", "sat", "saw", "say", "sea", "see", "set", "sew", "she", "shy",
  "sip", "sir", "sit", "six", "ski", "sky", "sly", "sob", "son", "sow", "soy", "spa",
  "spy", "sty", "sub", "sum", "sun",
  "tab", "tag", "tan", "tap", "tar", "tax", "tea", "ten", "the", "tie", "tin", "tip",
  "toe", "ton", "too", "top", "tot", "tow", "toy", "try", "tub", "tug", "two",
  "urn", "use",
  "van", "vat", "vet", "vie", "vow",
  "wag", "war", "was", "wax", "way", "web", "wed", "wet", "who", "why", "wig", "win",
  "wit", "woe", "wok", "won", "wow", "wry",
  "yak", "yam", "yap", "yes", "yet", "yew", "you", "yum",
  "zap", "zip", "zoo",
];

/** Kid-familiar four-letter words, for the longer ladders. */
export const WORDS_4: readonly string[] = [
  "able", "aces", "ache", "acre", "aide", "ants", "apes", "arch", "area", "arms", "army",
  "atom", "aunt", "away", "axes",
  "baby", "back", "bail", "bake", "bald", "bale", "ball", "band", "bang", "bank", "barn",
  "base", "bath", "bead", "beak", "beam", "bean", "bear", "beat", "beds", "beef", "been",
  "beep", "bees", "bell", "belt", "bend", "bent", "best", "bike", "bill", "bind", "bird",
  "bite", "blue", "boar", "boat", "body", "boil", "bold", "bolt", "bone", "book", "boom",
  "boot", "bore", "born", "boss", "both", "bowl", "brag", "bran", "brew", "brim", "buds",
  "bugs", "bulb", "bull", "bump", "bunk", "burn", "bush", "busy", "byte",
  "cage", "cake", "calf", "call", "calm", "came", "camp", "cane", "cape", "card", "care",
  "cart", "case", "cash", "cast", "cats", "cave", "cell", "cent", "chat", "chew", "chin",
  "chip", "chop", "city", "clam", "clap", "claw", "clay", "clip", "club", "clue", "coal",
  "coat", "code", "coil", "coin", "cold", "colt", "comb", "come", "cone", "cook", "cool",
  "cope", "cord", "core", "cork", "corn", "cost", "cosy", "cove", "cows", "crab", "crew",
  "crib", "crop", "crow", "cube", "cubs", "cuff", "cure", "curl", "cute",
  "damp", "dare", "dark", "darn", "dart", "dash", "date", "dawn", "days", "dead", "deal",
  "dear", "deed", "deep", "deer", "dent", "desk", "dial", "dice", "diet", "dime", "dine",
  "dish", "disk", "dive", "dock", "does", "dogs", "doll", "dome", "done", "doom", "door",
  "dose", "dots", "dove", "down", "drag", "draw", "drew", "drip", "drop", "drum", "duck",
  "dude", "dull", "dump", "dune", "dusk", "dust", "duty",
  "each", "earn", "ears", "ease", "east", "easy", "eats", "echo", "edge", "eggs", "else",
  "ends", "even", "ever", "exit", "eyes",
  "face", "fact", "fade", "fail", "fair", "fake", "fall", "fame", "fang", "fare", "farm",
  "fast", "fate", "fawn", "fear", "feed", "feel", "fees", "feet", "fell", "felt", "fern",
  "figs", "file", "fill", "film", "find", "fine", "fire", "firm", "fish", "fist", "five",
  "fizz", "flag", "flap", "flat", "flea", "fled", "flew", "flip", "flop", "flow", "foal",
  "foam", "foil", "fold", "folk", "fond", "font", "food", "fool", "foot", "ford", "fork",
  "form", "fort", "four", "fowl", "free", "frog", "from", "fuel", "full", "fume", "fund",
  "fuse", "fuss",
  "gain", "gale", "game", "gate", "gave", "gaze", "gear", "gems", "gift", "gill", "girl",
  "give", "glad", "glow", "glue", "goal", "goat", "gold", "golf", "gone", "gong", "good",
  "gown", "grab", "gram", "gray", "grew", "grid", "grin", "grip", "grow", "gulf", "gull",
  "gulp", "gust",
  "hail", "hair", "half", "hall", "halt", "hand", "hang", "hard", "hare", "harm", "harp",
  "hash", "have", "hawk", "hays", "haze", "head", "heal", "heap", "hear", "heat", "heed",
  "heel", "held", "helm", "help", "hens", "herb", "herd", "here", "hero", "hide", "high",
  "hike", "hill", "hilt", "hind", "hint", "hire", "hive", "hoax", "hold", "hole", "home",
  "hood", "hoof", "hook", "hoop", "hope", "horn", "hose", "host", "hour", "howl", "huge",
  "hulk", "hull", "hums", "hunt", "hurl", "hurt", "hush", "hymn",
  "idea", "inch", "into", "iron", "isle", "itch", "item",
  "jail", "jars", "jazz", "jeep", "jest", "jets", "jobs", "jogs", "join", "joke", "jolt",
  "jump", "junk", "just",
  "keel", "keen", "keep", "kelp", "kept", "keys", "kick", "kids", "kiln", "kind", "king",
  "kiss", "kite", "kits", "knee", "knew", "knit", "knob", "knot", "know",
  "lace", "lack", "lady", "laid", "lake", "lamb", "lame", "lamp", "land", "lane", "lark",
  "lash", "last", "late", "lawn", "laws", "lays", "lazy", "lead", "leaf", "leak", "lean",
  "leap", "left", "legs", "lend", "lens", "lent", "less", "lick", "lids", "life", "lift",
  "like", "lime", "limp", "line", "link", "lint", "lion", "lips", "list", "live", "load",
  "loaf", "loan", "lock", "loft", "logs", "lone", "long", "look", "loom", "loop", "loot",
  "lord", "lose", "loss", "lost", "loud", "love", "luck", "lump", "lung", "lure", "lush",
  "made", "maid", "mail", "main", "make", "male", "mall", "malt", "mane", "many", "maps",
  "mare", "mark", "mash", "mask", "mast", "mate", "math", "mats", "maze", "meal", "mean",
  "meat", "meet", "melt", "mend", "menu", "mice", "mild", "mile", "milk", "mill", "mind",
  "mine", "mint", "miss", "mist", "moan", "moat", "mock", "mode", "mold", "mole", "monk",
  "mood", "moon", "moor", "mope", "more", "morn", "moss", "most", "moth", "move", "much",
  "mule", "must", "mute",
  "nail", "name", "nape", "near", "neat", "neck", "need", "nest", "nets", "news", "next",
  "nice", "nine", "node", "none", "noon", "nope", "nose", "note", "noun", "numb", "nuts",
  "oaks", "oars", "oath", "oats", "obey", "odds", "once", "only", "onto", "open", "oval",
  "oven", "over", "owls", "owns",
  "pace", "pack", "pact", "page", "paid", "pail", "pain", "pair", "pale", "palm", "pane",
  "pans", "pant", "park", "part", "pass", "past", "path", "pave", "pawn", "pays", "peak",
  "peal", "pear", "peas", "peck", "peel", "peep", "peer", "pens", "pest", "pets", "pick",
  "pier", "pigs", "pike", "pile", "pill", "pine", "pink", "pins", "pint", "pipe", "pits",
  "pity", "plan", "play", "plot", "plow", "plug", "plum", "plus", "poem", "poet", "pole",
  "polo", "pond", "pony", "pool", "poor", "pope", "pork", "port", "pose", "post", "pots",
  "pour", "pram", "pray", "prey", "prop", "prow", "pull", "pulp", "pump", "pups", "pure",
  "push",
  "quit", "quiz",
  "race", "rack", "raft", "rage", "raid", "rail", "rain", "rake", "ramp", "rang", "rank",
  "rant", "rare", "rash", "rate", "rats", "rave", "read", "real", "reap", "rear", "reed",
  "reef", "reel", "rely", "rent", "rest", "rice", "rich", "ride", "rift", "ring", "rink",
  "ripe", "rise", "risk", "road", "roam", "roar", "robe", "rock", "rode", "role", "roll",
  "roof", "room", "root", "rope", "rose", "rows", "rude", "rugs", "rule", "runs", "rush",
  "rust",
  "sack", "safe", "sage", "said", "sail", "sake", "sale", "salt", "same", "sand", "sang",
  "sank", "save", "scan", "scar", "seal", "seam", "seat", "seed", "seek", "seem", "seen",
  "self", "sell", "send", "sent", "shed", "shin", "ship", "shoe", "shop", "shot", "show",
  "shut", "sick", "side", "sift", "sigh", "sign", "silk", "sill", "sing", "sink", "site",
  "size", "skin", "skip", "skis", "slam", "slap", "sled", "slid", "slim", "slip", "slot",
  "slow", "snap", "snow", "soak", "soap", "sock", "soda", "sofa", "soft", "soil", "sold",
  "sole", "solo", "some", "song", "soon", "sore", "sort", "soul", "soup", "sour", "spin",
  "spot", "spun", "star", "stay", "stem", "step", "stew", "stir", "stop", "stub", "such",
  "suit", "sung", "sunk", "sure", "surf", "swan", "swap", "swim",
  "tack", "tail", "take", "tale", "talk", "tall", "tame", "tank", "tape", "task", "team",
  "tear", "teen", "tell", "tend", "tent", "term", "test", "text", "than", "that", "them",
  "then", "they", "thin", "this", "tide", "tidy", "tied", "tile", "till", "tilt", "time",
  "tiny", "tire", "toad", "toes", "told", "toll", "tomb", "tone", "took", "tool", "toot",
  "torn", "toss", "tour", "town", "toys", "trap", "tray", "tree", "trim", "trip", "trot",
  "true", "tube", "tuck", "tune", "turn", "twig", "twin", "type",
  "ugly", "unit", "upon", "used",
  "vain", "vane", "vase", "vast", "veal", "veil", "vent", "verb", "very", "vest", "vine",
  "visa", "void", "vole", "volt", "vote", "vows",
  "wade", "wage", "wail", "wait", "wake", "walk", "wall", "wand", "want", "ward", "warm",
  "warn", "wart", "wash", "wasp", "wave", "waxy", "ways", "weak", "wear", "weed", "week",
  "weep", "well", "went", "were", "west", "what", "when", "whip", "whom", "wide", "wife",
  "wild", "will", "wilt", "wind", "wing", "wink", "wipe", "wire", "wise", "wish", "wisp",
  "with", "wolf", "wood", "wool", "word", "wore", "work", "worm", "worn", "wrap", "wren",
  "yard", "yarn", "yawn", "year", "yell", "yolk", "your",
  "zeal", "zero", "zest", "zinc", "zone", "zoom",
];
